export interface PromptConfig {
  name: string;
  role: string;
  context: string;
  objective: string;
  constraints: string;
  examples: string;
  outputFormat: string;
}

export const defaultExamples: PromptConfig[] = [
  {
    name: "Blog Writer",
    role: "You are an expert blog writer specializing in technology.",
    context: "The topic is about Artificial Intelligence in healthcare.",
    objective:
      "Write a blog post that explains the impact of AI on patient diagnosis.",
    constraints: "Keep the language simple and engaging. Limit to 500 words.",
    examples: "For example, explain how AI is already being used in radiology.",
    outputFormat:
      "Output should be a blog-style article with paragraphs and subheadings.",
  },
  {
    name: "Code Reviewer",
    role: "You are a senior software engineer reviewing code.",
    context: "The user provides JavaScript code snippets.",
    objective:
      "Provide constructive feedback on performance, readability, and best practices.",
    constraints: "Be concise. Avoid rewriting the code unless necessary.",
    examples:
      "If a loop can be replaced with a built-in method, point that out.",
    outputFormat: "Return structured feedback in bullet points.",
  },
];

export const HEDGING_WORDS: string[] = [
  "a bit",
  "a little",
  "almost",
  "apparently",
  "appear",
  "around",
  "basically",
  "can",
  "could",
  "essentially",
  "fairly",
  "hopefully",
  "in a sense",
  "in my opinion",
  "just",
  "kind of",
  "largely",
  "likely",
  "mainly",
  "may",
  "maybe",
  "might",
  "mostly",
  "often",
  "overall",
  "perhaps",
  "possibly",
  "pretty",
  "probably",
  "quite",
  "rather",
  "really",
  "relatively",
  "roughly",
  "seems",
  "should",
  "sometimes",
  "somewhat",
  "sort of",
  "suggests",
  "supposedly",
  "tend to",
  "typically",
];

export const GENERIC_VERBS: string[] = [
  "be",
  "do",
  "get",
  "give",
  "go",
  "have",
  "make",
  "put",
  "say",
  "see",
  "take",
];

export const STRONG_ACTION_VERBS: string[] = [
  "act as",
  "analyze",
  "assess",
  "brainstorm",
  "build",
  "classify",
  "compare",
  "compose",
  "contrast",
  "convert",
  "create",
  "critique",
  "debug",
  "define",
  "design",
  "develop",
  "diagnose",
  "draft",
  "edit",
  "evaluate",
  "explain",
  "extract",
  "format",
  "generate",
  "identify",
  "illustrate",
  "improve",
  "interpret",
  "invent",
  "list",
  "optimize",
  "outline",
  "paraphrase",
  "predict",
  "proofread",
  "propose",
  "rank",
  "rate",
  "refactor",
  "refine",
  "rephrase",
  "restate",
  "rewrite",
  "simplify",
  "solve",
  "structure",
  "suggest",
  "summarize",
  "synthesize",
  "trace",
  "transcribe",
  "transform",
  "translate",
];

export const OUTPUT_FORMAT_KEYWORDS: string[] = [
  "array",
  "article",
  "blog post",
  "bullet points",
  "chart",
  "code block",
  "csv",
  "email",
  "essay",
  "html",
  "javascript",
  "json",
  "json object",
  "list",
  "markdown",
  "numbered list",
  "object",
  "paragraph",
  "poem",
  "python",
  "report",
  "script",
  "sql",
  "table",
  "text",
  "typescript",
  "xml",
  "yaml",
];
